apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: schedulerv2-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: schedulerv2
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
